description: "A personal website"

url: "StevenUlin.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

title: Steven Ulin

author :
  name : Steven Ulin
  title : Mathematician
  email : ulins@rpi.edu
  
  
ASSET_PATH : /assets
