description: "A personal website"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

title: Steven Ulin

author :
  name : Steven Ulin
  title : Mathematician
  email : ulins@rpi.edu
