description: "A personal website"

url: "steveulin.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

title: Steven Ulin

author :
  name : Steven Ulin
  title : Software Engineer
  email : SteveUlin@rpi.edu
  
BASE_PATH : false
